services:
  database:
    image: mysql:8.2
    container_name: mysql_laravel
    volumes:
      - volume_db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: easyleekdatabase
    ports:
      - 8002:3306
    networks:
      - monreseau

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_laravel
    ports:
      - 9000:80
    environment:
      environment:
      PMA_HOST: database
    networks:
      - monreseau
    depends_on:
      - database

  easyleekcertif:
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: easyleekcertif
    restart: always
    ports:
      - 8001:80
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - monreseau

volumes:
  volume_db:
networks:
  monreseau:
